allow_licenses:
  - 'Apache-2.0'
  - '0BSD'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'MIT-CMU'
  - 'ISC'
  - 'MPL-1.1'
  - 'MPL-2.0'
  - 'PSF-2.0'
  - 'LGPL-2.1'
  - 'LGPL-2.1-or-later'
  - 'LGPL-2.1-only'
  - 'Unlicense'
