name: Build Container images

# this workflow will be triggered manually from workflows needing the images
on:
  push:
    paths:
      - .github/workflows/build-container-images.yaml
  workflow_call:

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - name: bundled
            containerfile: Containerfile
            context: .
          - name: backend
            containerfile: backend/Containerfile
            context: backend/
          - name: frontend
            containerfile: frontend/Containerfile
            context: frontend/
          - name: reis
            containerfile: services/reis/Containerfile
            context: services/reis/
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.containerfile }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.service.name }}:commit-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
